export enum ErrorCode {
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  RECEIPT_BOOK_NOT_FOUND = 'RECEIPT_BOOK_NOT_FOUND',
  BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',
  RECEIPT_BOOK_INACTIVE = 'RECEIPT_BOOK_INACTIVE',
  NO_PENDING_SERVICES = 'NO_PENDING_SERVICES',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
